services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    volumes:
      - ./web:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./web:/var/www/html
    env_file:
      - ./.env
    networks:
      - inception

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - inception

networks:
  inception:
